behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 3048
      buffer_size: 30480
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 8
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 20
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 15000000
    time_horizon: 1200
    summary_freq: 9000
    self_play:
      save_steps: 55000
      team_change: 90000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
