behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 6048
      buffer_size: 30480
      learning_rate: 0.0005
      beta: 0.004
      epsilon: 0.25
      lambd: 0.9
      num_epoch: 8
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 10
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 2000
    summary_freq: 5000
    self_play:
      save_steps: 50000
      team_change: 50000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
